#!/bin/bash
#############################################################################
# Somatic Mutation Workflow - Annovar Annotation Script
# This script performs Annovar annotation on the VCF files generated by Mutect2.
#############################################################################

# function to annotate a single sample
funcotator_annotation() {
    
    local tumour_id=$1

    ## Annotate variants by Funcotator
    echo "$(date +"%F") $(date +"%T") - (${tumour_id}) Annotating variants with Funcotator ..."
    
    singularity exec \
        --bind "${PROJECT_DIR}:${PROJECT_DIR}" \
        --bind "${MUTECT2_DIR}:${MUTECT2_DIR}" \
        --bind /tmp:/tmp \
        "${container_dir}/gatk.sif" \
        gatk Funcotator \
            -R "${REFERENCE}" \
            -V "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.final.vcf.gz" \
            -O "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.funcotator.maf.gz" \
            -L "${INTERVAL}" \
            --output-file-format MAF \
            --data-sources-path "${ANNOTATION_FILE}" \
            --ref-version hg38 \
            --remove-filtered-variants true \
            >& "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.funcotator.log"

    if [[ $? -ne 0 ]]; then
        echo "ERROR: Funcotator failed for ${tumour_id}" >&2
        return 1
    fi

    # Extract relevant columns from the Funcotator output
    less -S "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.funcotator.maf.gz" |
        grep -v "#" > "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.funcotator.tsv"
}