#!/bin/bash

#############################################################################
## Somatic Mutation Workflow - Annovar Annotation Script
## Author:  Zhong Guorui
## This script performs Annovar annotation on the VCF files generated by Mutect2.
#############################################################################

## Create the output directory
mkdir -p "${ANNOVAR_DIR}"

## "==========================================================================="
## Function to annotate a single sample
## "==========================================================================="
annovar_annotation() {
    
    local tumour_id=$1
    
    echo "$(date +"%F") $(date +"%T") - (${tumour_id}) Annovar annotation ..."
    
    output_dir="${ANNOVAR_DIR}/${tumour_id}"
    mkdir -p "${output_dir}"

    perl "${SOFTWARE_DIR}/annovar/table_annovar.pl" \
        "${MUTECT2_DIR}/${tumour_id}/${tumour_id}.final.vcf.gz" \
        "${SOFTWARE_DIR}/annovar/humandb/" \
        -buildver hg38 \
        -out "${output_dir}/${tumour_id}" \
        -remove \
        -protocol refGene,cytoBand,dbnsfp33a,gnomad_exome,avsnp150,clinvar_20221231,cosmic70 \
        -operation gx,r,f,f,f,f,f \
        -nastring . \
        -polish \
        -xreffile "${REFERENCE_DIR}/annovar/example/gene_fullxref.txt" \
        --otherinfo \
        --vcfinput \
        >& "${output_dir}/${tumour_id}.annovar.log"

    # Extract relevant columns from the Annovar output
    less -S "${output_dir}/${tumour_id}.hg38_multianno.txt" |
        awk 'BEGIN {FS=OFS="\t"} NR==1 {print $0, "AD", "AF", "DP"}; NR >1 {split($NF, a, ":"); $(NF+1)=a[2]; $(NF+1)=a[3]; $(NF+1)=a[4]; print}' > \
            "${output_dir}/${tumour_id}.annovar.txt"
}

export -f annovar_annotation

## "==========================================================================="
## Run Annovar annotation for all samples
## "==========================================================================="
tumour_ids=$(find "${MUTECT2_DIR}" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | grep "T" | sort)

echo "${tumour_ids}" | parallel --jobs "$PARALLEL_JOBS" annovar_annotation {}